import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * Flat ESLint config for the Drug Tracker Vite + React SPA.
 *
 * Based on the standard Vite + React + TypeScript template ESLint setup,
 * adapted to a plain Vite SPA (no TanStack Start, no SSR, no auth routes).
 */
export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'public/aistudio/**',
      'public/assets/**',
      // Capacitor native project — generated by `npx cap add android`.
      // Contains minified/bundled web assets that ESLint cannot
      // meaningfully analyze (the original source lives in src/).
      'android/**',
      'ios/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx,js,jsx,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  // Disable rules that conflict with Prettier formatting.
  prettier,
);
